### ISSUE TITLE
Laravel Livewire ID problem

### ISSUE THREAD

**Issue by ioanschmitt** [kra8/laravel-snowflake#30]
Hi, I have a problem, I am using Laravel Jetstream with the Livewire stack, everything is working fine except one thing.

When I try to update a Model, Livewire gives me an error 
`Livewire encountered corrupt data when trying to hydrate the [legal-entities.edit-page] component. Ensure that the [name, id, data] of the Livewire component wasn't tampered with between requests.`

After some digging I found out, that the ids for the model are not matching!

Lets say the model has an id of `432224099704639488` but in the error, under Livewire serverMemo, it says, it has an id of `432224099704639500`, a very small difference. How can that be? There is no model with the id of `432224099704639500`.

Do you have a clue what is going on?

**Comment by kra8** [comment]
Probably because JavaScript rounds the numbers.

Try casting the ID to a string as shown below.
``` php
class Sample extends Model
{
    use HasSnowflakePrimary;

    protected $casts = [
        'id' => 'string',
    ];
}
```

**Comment by ioanschmitt** [comment]
Ah yes, could have thought about it myself 😄 

I will try it later.

**Comment by ioanschmitt** [comment]
This did fix the problem!

Thank you!
