### ISSUE TITLE
generate duplicate ids when running  with php-fpm mode

### ISSUE THREAD

**Issue by jisheng100** [kra8/laravel-snowflake#37]
Hello,
 I use your package in php-fpm mode, and the generated id will be repeated under large concurrent requests.

`$router->get('/snowflake',function(){
    $snowflake = app('Kra8\Snowflake\Snowflake');
    $id = $snowflake->next();
    file_put_contents(storage_path().'/ids.txt',$id."\n",FILE_APPEND);
});`

and use ab test
`ab -c100 -n1000 http://dev.v8.com/snowflake`

It will generate duplicate ids

**Comment by kra8** [comment]
Hello, i am not good at English, so I use translation.

Since IDs are generated using timestamps, IDs may be duplicated if they are requested at exactly the same time.
My solution is to generate the ID again when it is duplicated.

**Comment by kra8** [comment]
Hi. In order to reduce duplication as much as possible, we have changed the sequence number to be random from v2.1.0.

This will almost never result in duplication, but if there are too many simultaneous requests, there may be some duplication.

**Comment by jisheng100** [comment]
Cool job!
thank you
