### ISSUE TITLE
Implicit conversion from float 1651699585.045 to int loses precision

### ISSUE THREAD

**Issue by seabasss** [kra8/laravel-snowflake#39]
I'm getting this message in my logs.

```
Implicit conversion from float 1651699585.045 to int loses precision in /vendor/kra8/laravel-snowflake/src/Snowflake.php on line 141
```

This is row 141:
`$datetime = date('Y-m-d H:i:s', ((($timestamp + $this->epoch) / 1000) | 0));`

Ideas? I'm running PHP 8.1.4. Thanks!

**Comment by kra8** [comment]
Thanks for finding it.
I fixed it.

**Comment by seabasss** [comment]
Awesome, thanks!
